# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gitc/preferences.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Preferences(object):
    def setupUi(self, Preferences):
        Preferences.setObjectName("Preferences")
        Preferences.resize(529, 316)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Preferences)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(Preferences)
        self.tabWidget.setObjectName("tabWidget")
        self.tabGeneral = QtWidgets.QWidget()
        self.tabGeneral.setObjectName("tabGeneral")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabGeneral)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tabGeneral)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cbEsc = QtWidgets.QCheckBox(self.groupBox_6)
        self.cbEsc.setObjectName("cbEsc")
        self.verticalLayout_5.addWidget(self.cbEsc)
        self.cbState = QtWidgets.QCheckBox(self.groupBox_6)
        self.cbState.setObjectName("cbState")
        self.verticalLayout_5.addWidget(self.cbState)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tabGeneral)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cbShowWhitespace = QtWidgets.QCheckBox(self.groupBox_5)
        self.cbShowWhitespace.setObjectName("cbShowWhitespace")
        self.horizontalLayout.addWidget(self.cbShowWhitespace)
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.sbTabSize = QtWidgets.QSpinBox(self.groupBox_5)
        self.sbTabSize.setMinimum(1)
        self.sbTabSize.setMaximum(8)
        self.sbTabSize.setProperty("value", 4)
        self.sbTabSize.setObjectName("sbTabSize")
        self.horizontalLayout.addWidget(self.sbTabSize)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.cbIgnoreWhitespace = QtWidgets.QComboBox(self.groupBox_5)
        self.cbIgnoreWhitespace.setObjectName("cbIgnoreWhitespace")
        self.cbIgnoreWhitespace.addItem("")
        self.cbIgnoreWhitespace.addItem("")
        self.cbIgnoreWhitespace.addItem("")
        self.horizontalLayout_3.addWidget(self.cbIgnoreWhitespace)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.tabWidget.addTab(self.tabGeneral, "")
        self.tabFonts = QtWidgets.QWidget()
        self.tabFonts.setObjectName("tabFonts")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabFonts)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabFonts)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cbSizeLog = QtWidgets.QComboBox(self.groupBox_3)
        self.cbSizeLog.setObjectName("cbSizeLog")
        self.gridLayout_3.addWidget(self.cbSizeLog, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.cbFamilyLog = QtWidgets.QFontComboBox(self.groupBox_3)
        self.cbFamilyLog.setObjectName("cbFamilyLog")
        self.gridLayout_3.addWidget(self.cbFamilyLog, 0, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabFonts)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cbFamilyDiff = QtWidgets.QFontComboBox(self.groupBox_4)
        self.cbFamilyDiff.setObjectName("cbFamilyDiff")
        self.gridLayout_4.addWidget(self.cbFamilyDiff, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 0, 1, 1)
        self.cbSizeDiff = QtWidgets.QComboBox(self.groupBox_4)
        self.cbSizeDiff.setObjectName("cbSizeDiff")
        self.gridLayout_4.addWidget(self.cbSizeDiff, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.tabFonts, "")
        self.tabSummary = QtWidgets.QWidget()
        self.tabSummary.setObjectName("tabSummary")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabSummary)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.tabSummary)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.colorB = ColorWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorB.sizePolicy().hasHeightForWidth())
        self.colorB.setSizePolicy(sizePolicy)
        self.colorB.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.colorB.setObjectName("colorB")
        self.gridLayout.addWidget(self.colorB, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.colorA = ColorWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorA.sizePolicy().hasHeightForWidth())
        self.colorA.setSizePolicy(sizePolicy)
        self.colorA.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.colorA.setObjectName("colorA")
        self.gridLayout.addWidget(self.colorA, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabSummary)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.leBugUrl = QtWidgets.QLineEdit(self.groupBox_2)
        self.leBugUrl.setObjectName("leBugUrl")
        self.gridLayout_2.addWidget(self.leBugUrl, 1, 1, 1, 1)
        self.leCommitUrl = QtWidgets.QLineEdit(self.groupBox_2)
        self.leCommitUrl.setObjectName("leCommitUrl")
        self.gridLayout_2.addWidget(self.leCommitUrl, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.leBugPattern = QtWidgets.QLineEdit(self.groupBox_2)
        self.leBugPattern.setObjectName("leBugPattern")
        self.gridLayout_2.addWidget(self.leBugPattern, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tabSummary, "")
        self.tabTools = QtWidgets.QWidget()
        self.tabTools.setObjectName("tabTools")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tabTools)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tabTools)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.groupBox_7)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_8.addWidget(self.label_12)
        self.tableView = QtWidgets.QTableView(self.groupBox_7)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_8.addWidget(self.tableView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnAdd = QtWidgets.QPushButton(self.groupBox_7)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout_2.addWidget(self.btnAdd)
        self.btnDelete = QtWidgets.QPushButton(self.groupBox_7)
        self.btnDelete.setObjectName("btnDelete")
        self.horizontalLayout_2.addWidget(self.btnDelete)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addWidget(self.groupBox_7)
        self.tabWidget.addTab(self.tabTools, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Preferences)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.label_10.setBuddy(self.sbTabSize)
        self.label_11.setBuddy(self.cbIgnoreWhitespace)
        self.label_6.setBuddy(self.cbFamilyLog)
        self.label_7.setBuddy(self.cbSizeLog)
        self.label_9.setBuddy(self.cbSizeDiff)
        self.label_8.setBuddy(self.cbFamilyDiff)
        self.label_2.setBuddy(self.colorB)
        self.label.setBuddy(self.colorA)
        self.label_3.setBuddy(self.leCommitUrl)
        self.label_4.setBuddy(self.leBugUrl)
        self.label_5.setBuddy(self.leBugPattern)

        self.retranslateUi(Preferences)
        self.tabWidget.setCurrentIndex(3)
        self.buttonBox.accepted.connect(Preferences.accept)
        self.buttonBox.rejected.connect(Preferences.reject)
        QtCore.QMetaObject.connectSlotsByName(Preferences)
        Preferences.setTabOrder(self.btnAdd, self.tableView)
        Preferences.setTabOrder(self.tableView, self.cbSizeDiff)
        Preferences.setTabOrder(self.cbSizeDiff, self.colorA)
        Preferences.setTabOrder(self.colorA, self.colorB)
        Preferences.setTabOrder(self.colorB, self.leCommitUrl)
        Preferences.setTabOrder(self.leCommitUrl, self.leBugUrl)
        Preferences.setTabOrder(self.leBugUrl, self.leBugPattern)
        Preferences.setTabOrder(self.leBugPattern, self.buttonBox)
        Preferences.setTabOrder(self.buttonBox, self.cbEsc)
        Preferences.setTabOrder(self.cbEsc, self.cbState)
        Preferences.setTabOrder(self.cbState, self.cbShowWhitespace)
        Preferences.setTabOrder(self.cbShowWhitespace, self.sbTabSize)
        Preferences.setTabOrder(self.sbTabSize, self.cbIgnoreWhitespace)
        Preferences.setTabOrder(self.cbIgnoreWhitespace, self.cbFamilyDiff)
        Preferences.setTabOrder(self.cbFamilyDiff, self.tabWidget)
        Preferences.setTabOrder(self.tabWidget, self.cbFamilyLog)
        Preferences.setTabOrder(self.cbFamilyLog, self.cbSizeLog)

    def retranslateUi(self, Preferences):
        _translate = QtCore.QCoreApplication.translate
        Preferences.setWindowTitle(_translate("Preferences", "Preferences"))
        self.groupBox_6.setTitle(_translate("Preferences", "Application"))
        self.cbEsc.setText(_translate("Preferences", "&Quit also via Esc key"))
        self.cbState.setText(_translate("Preferences", "&Remember window state"))
        self.groupBox_5.setTitle(_translate("Preferences", "Diff view"))
        self.cbShowWhitespace.setText(_translate("Preferences", "&Visualize whitespace"))
        self.label_10.setText(_translate("Preferences", "&Tab size:"))
        self.label_11.setText(_translate("Preferences", "&Ignore whitespace:"))
        self.cbIgnoreWhitespace.setItemText(0, _translate("Preferences", "None"))
        self.cbIgnoreWhitespace.setItemText(1, _translate("Preferences", "At end of line"))
        self.cbIgnoreWhitespace.setItemText(2, _translate("Preferences", "All"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeneral), _translate("Preferences", "&General"))
        self.groupBox_3.setTitle(_translate("Preferences", "Log view"))
        self.label_6.setText(_translate("Preferences", "&Family:"))
        self.label_7.setText(_translate("Preferences", "&Size:"))
        self.groupBox_4.setTitle(_translate("Preferences", "Diff view"))
        self.label_9.setText(_translate("Preferences", "S&ize:"))
        self.label_8.setText(_translate("Preferences", "F&amily:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFonts), _translate("Preferences", "&Fonts"))
        self.groupBox.setTitle(_translate("Preferences", "Color"))
        self.label_2.setText(_translate("Preferences", "Branch &B:"))
        self.label.setText(_translate("Preferences", "Branch &A:"))
        self.groupBox_2.setTitle(_translate("Preferences", "Links"))
        self.label_3.setText(_translate("Preferences", "C&ommit URL:"))
        self.label_4.setText(_translate("Preferences", "B&UG URL:"))
        self.label_5.setText(_translate("Preferences", "BUG &Pattern:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSummary), _translate("Preferences", "Co&mmit"))
        self.groupBox_7.setTitle(_translate("Preferences", "Tools"))
        self.label_12.setText(_translate("Preferences", "You must add the tool to git config mergetool/difftool section to make it works."))
        self.btnAdd.setText(_translate("Preferences", "&Add"))
        self.btnDelete.setText(_translate("Preferences", "&Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTools), _translate("Preferences", "&Tools"))
from .colorwidget import ColorWidget
