# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/gitview.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GitView(object):
    def setupUi(self, GitView):
        GitView.setObjectName("GitView")
        GitView.resize(668, 630)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(GitView)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.branchSpinner = QtWaitingSpinner(GitView)
        self.branchSpinner.setObjectName("branchSpinner")
        self.horizontalLayout.addWidget(self.branchSpinner)
        self.lbBranch = QtWidgets.QLabel(GitView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbBranch.sizePolicy().hasHeightForWidth())
        self.lbBranch.setSizePolicy(sizePolicy)
        self.lbBranch.setObjectName("lbBranch")
        self.horizontalLayout.addWidget(self.lbBranch)
        self.cbBranch = QtWidgets.QComboBox(GitView)
        self.cbBranch.setObjectName("cbBranch")
        self.horizontalLayout.addWidget(self.cbBranch)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.splitter = QtWidgets.QSplitter(GitView)
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.logWidget = QtWidgets.QSplitter(self.splitter)
        self.logWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.logWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.logWidget.setOrientation(QtCore.Qt.Horizontal)
        self.logWidget.setHandleWidth(1)
        self.logWidget.setObjectName("logWidget")
        self.logGraph = LogGraph(self.logWidget)
        self.logGraph.setObjectName("logGraph")
        self.logView = LogView(self.logWidget)
        self.logView.setObjectName("logView")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.diffSpinner = QtWaitingSpinner(self.verticalLayoutWidget)
        self.diffSpinner.setObjectName("diffSpinner")
        self.horizontalLayout_2.addWidget(self.diffSpinner)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.leSha1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.leSha1.setObjectName("leSha1")
        self.horizontalLayout_2.addWidget(self.leSha1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.findSpinner = QtWaitingSpinner(self.verticalLayoutWidget)
        self.findSpinner.setObjectName("findSpinner")
        self.horizontalLayout_3.addWidget(self.findSpinner)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.cbFindWhat = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cbFindWhat.setObjectName("cbFindWhat")
        self.cbFindWhat.addItem("")
        self.cbFindWhat.addItem("")
        self.cbFindWhat.addItem("")
        self.horizontalLayout_3.addWidget(self.cbFindWhat)
        self.leFindWhat = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.leFindWhat.setObjectName("leFindWhat")
        self.horizontalLayout_3.addWidget(self.leFindWhat)
        self.cbFindType = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cbFindType.setObjectName("cbFindType")
        self.cbFindType.addItem("")
        self.cbFindType.addItem("")
        self.cbFindType.addItem("")
        self.horizontalLayout_3.addWidget(self.cbFindType)
        self.tbPrev = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.tbPrev.setObjectName("tbPrev")
        self.horizontalLayout_3.addWidget(self.tbPrev)
        self.tbNext = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.tbNext.setObjectName("tbNext")
        self.horizontalLayout_3.addWidget(self.tbNext)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.diffView = DiffView(self.verticalLayoutWidget)
        self.diffView.setObjectName("diffView")
        self.verticalLayout.addWidget(self.diffView)
        self.verticalLayout_2.addWidget(self.splitter)

        self.retranslateUi(GitView)
        QtCore.QMetaObject.connectSlotsByName(GitView)
        GitView.setTabOrder(self.cbBranch, self.logWidget)
        GitView.setTabOrder(self.logWidget, self.leSha1)
        GitView.setTabOrder(self.leSha1, self.cbFindWhat)
        GitView.setTabOrder(self.cbFindWhat, self.leFindWhat)
        GitView.setTabOrder(self.leFindWhat, self.cbFindType)
        GitView.setTabOrder(self.cbFindType, self.tbPrev)
        GitView.setTabOrder(self.tbPrev, self.tbNext)

    def retranslateUi(self, GitView):
        _translate = QtCore.QCoreApplication.translate
        GitView.setWindowTitle(_translate("GitView", "GitView"))
        self.lbBranch.setText(_translate("GitView", "Branch:"))
        self.label.setText(_translate("GitView", "SHA1 ID:"))
        self.label_3.setText(_translate("GitView", "Find"))
        self.label_2.setText(_translate("GitView", "commit"))
        self.cbFindWhat.setItemText(0, _translate("GitView", "adding/removing string"))
        self.cbFindWhat.setItemText(1, _translate("GitView", "changing lines matching"))
        self.cbFindWhat.setItemText(2, _translate("GitView", "containing"))
        self.leFindWhat.setPlaceholderText(_translate("GitView", "Press Enter to find commits"))
        self.cbFindType.setItemText(0, _translate("GitView", "Exact"))
        self.cbFindType.setItemText(1, _translate("GitView", "Ignore case"))
        self.cbFindType.setItemText(2, _translate("GitView", "Regexp"))
        self.tbPrev.setToolTip(_translate("GitView", "Find previous"))
        self.tbPrev.setText(_translate("GitView", "↑"))
        self.tbNext.setToolTip(_translate("GitView", "Find next"))
        self.tbNext.setText(_translate("GitView", "↓"))


from diffview import DiffView
from logview import LogGraph, LogView
from waitingspinnerwidget import QtWaitingSpinner
