# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridFrame.sizePolicy().hasHeightForWidth())
        self.gridFrame.setSizePolicy(sizePolicy)
        self.gridFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.gridFrame.setObjectName(_fromUtf8("gridFrame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridFrame)
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.gridFrame)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.cbPatternType = QtGui.QComboBox(self.gridFrame)
        self.cbPatternType.setObjectName(_fromUtf8("cbPatternType"))
        self.cbPatternType.addItem(_fromUtf8(""))
        self.cbPatternType.addItem(_fromUtf8(""))
        self.cbPatternType.addItem(_fromUtf8(""))
        self.cbPatternType.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cbPatternType, 1, 0, 1, 1)
        self.leRepo = QtGui.QLineEdit(self.gridFrame)
        self.leRepo.setObjectName(_fromUtf8("leRepo"))
        self.gridLayout_2.addWidget(self.leRepo, 0, 1, 1, 1)
        self.btnRepoBrowse = QtGui.QPushButton(self.gridFrame)
        self.btnRepoBrowse.setObjectName(_fromUtf8("btnRepoBrowse"))
        self.gridLayout_2.addWidget(self.btnRepoBrowse, 0, 2, 1, 1)
        self.lePattern = QtGui.QLineEdit(self.gridFrame)
        self.lePattern.setObjectName(_fromUtf8("lePattern"))
        self.gridLayout_2.addWidget(self.lePattern, 1, 1, 1, 1)
        self.btnFileSelect = QtGui.QPushButton(self.gridFrame)
        self.btnFileSelect.setObjectName(_fromUtf8("btnFileSelect"))
        self.gridLayout_2.addWidget(self.btnFileSelect, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.gridFrame)
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setFrameShape(QtGui.QFrame.StyledPanel)
        self.splitter.setFrameShadow(QtGui.QFrame.Plain)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.gitViewA = GitView(self.splitter)
        self.gitViewA.setObjectName(_fromUtf8("gitViewA"))
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        self.menu_Settings = QtGui.QMenu(self.menubar)
        self.menu_Settings.setObjectName(_fromUtf8("menu_Settings"))
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName(_fromUtf8("menu_View"))
        self.menuIgnoreWhitespace = QtGui.QMenu(self.menu_View)
        self.menuIgnoreWhitespace.setObjectName(_fromUtf8("menuIgnoreWhitespace"))
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName(_fromUtf8("menu_Edit"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.acQuit = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("application-exit"))
        self.acQuit.setIcon(icon)
        self.acQuit.setObjectName(_fromUtf8("acQuit"))
        self.acAbout = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("help-about"))
        self.acAbout.setIcon(icon)
        self.acAbout.setObjectName(_fromUtf8("acAbout"))
        self.acPreferences = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("preferences-system"))
        self.acPreferences.setIcon(icon)
        self.acPreferences.setObjectName(_fromUtf8("acPreferences"))
        self.actionIgnore_whitespace_changes = QtGui.QAction(MainWindow)
        self.actionIgnore_whitespace_changes.setObjectName(_fromUtf8("actionIgnore_whitespace_changes"))
        self.acVisualizeWhitespace = QtGui.QAction(MainWindow)
        self.acVisualizeWhitespace.setCheckable(True)
        self.acVisualizeWhitespace.setObjectName(_fromUtf8("acVisualizeWhitespace"))
        self.acIgnoreEOL = QtGui.QAction(MainWindow)
        self.acIgnoreEOL.setCheckable(True)
        self.acIgnoreEOL.setObjectName(_fromUtf8("acIgnoreEOL"))
        self.acIgnoreAll = QtGui.QAction(MainWindow)
        self.acIgnoreAll.setCheckable(True)
        self.acIgnoreAll.setObjectName(_fromUtf8("acIgnoreAll"))
        self.acIgnoreNone = QtGui.QAction(MainWindow)
        self.acIgnoreNone.setCheckable(True)
        self.acIgnoreNone.setObjectName(_fromUtf8("acIgnoreNone"))
        self.acCopy = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-copy"))
        self.acCopy.setIcon(icon)
        self.acCopy.setObjectName(_fromUtf8("acCopy"))
        self.acSelectAll = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-select-all"))
        self.acSelectAll.setIcon(icon)
        self.acSelectAll.setObjectName(_fromUtf8("acSelectAll"))
        self.acFind = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-find"))
        self.acFind.setIcon(icon)
        self.acFind.setObjectName(_fromUtf8("acFind"))
        self.acCompare = QtGui.QAction(MainWindow)
        self.acCompare.setCheckable(True)
        self.acCompare.setObjectName(_fromUtf8("acCompare"))
        self.acShowGraph = QtGui.QAction(MainWindow)
        self.acShowGraph.setCheckable(True)
        self.acShowGraph.setChecked(True)
        self.acShowGraph.setObjectName(_fromUtf8("acShowGraph"))
        self.acAboutQt = QtGui.QAction(MainWindow)
        self.acAboutQt.setObjectName(_fromUtf8("acAboutQt"))
        self.menuFile.addAction(self.acQuit)
        self.menu_Help.addAction(self.acAbout)
        self.menu_Help.addAction(self.acAboutQt)
        self.menu_Settings.addAction(self.acPreferences)
        self.menuIgnoreWhitespace.addAction(self.acIgnoreNone)
        self.menuIgnoreWhitespace.addAction(self.acIgnoreEOL)
        self.menuIgnoreWhitespace.addAction(self.acIgnoreAll)
        self.menu_View.addAction(self.acVisualizeWhitespace)
        self.menu_View.addAction(self.menuIgnoreWhitespace.menuAction())
        self.menu_View.addSeparator()
        self.menu_View.addAction(self.acShowGraph)
        self.menu_View.addSeparator()
        self.menu_View.addAction(self.acCompare)
        self.menu_Edit.addAction(self.acCopy)
        self.menu_Edit.addAction(self.acSelectAll)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.acFind)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_Settings.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.leRepo, self.btnRepoBrowse)
        MainWindow.setTabOrder(self.btnRepoBrowse, self.cbPatternType)
        MainWindow.setTabOrder(self.cbPatternType, self.lePattern)
        MainWindow.setTabOrder(self.lePattern, self.btnFileSelect)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "gitc", None))
        self.label.setText(_translate("MainWindow", "Repositories:", None))
        self.cbPatternType.setItemText(0, _translate("MainWindow", "File Path", None))
        self.cbPatternType.setItemText(1, _translate("MainWindow", "Commit Pattern", None))
        self.cbPatternType.setItemText(2, _translate("MainWindow", "Author", None))
        self.cbPatternType.setItemText(3, _translate("MainWindow", "Committer", None))
        self.btnRepoBrowse.setText(_translate("MainWindow", "&Browse...", None))
        self.lePattern.setPlaceholderText(_translate("MainWindow", "Type keyword here and press Enter to filter", None))
        self.btnFileSelect.setText(_translate("MainWindow", "&Choose...", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help", None))
        self.menu_Settings.setTitle(_translate("MainWindow", "&Settings", None))
        self.menu_View.setTitle(_translate("MainWindow", "&View", None))
        self.menuIgnoreWhitespace.setTitle(_translate("MainWindow", "&Ignore whitespace", None))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit", None))
        self.acQuit.setText(_translate("MainWindow", "&Quit", None))
        self.acQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.acAbout.setText(_translate("MainWindow", "&About gitc", None))
        self.acPreferences.setText(_translate("MainWindow", "&Preferences...", None))
        self.actionIgnore_whitespace_changes.setText(_translate("MainWindow", "Ignore whitespace changes", None))
        self.acVisualizeWhitespace.setText(_translate("MainWindow", "&Visualize whitespace", None))
        self.acIgnoreEOL.setText(_translate("MainWindow", "At &end of line", None))
        self.acIgnoreAll.setText(_translate("MainWindow", "&All", None))
        self.acIgnoreNone.setText(_translate("MainWindow", "&None", None))
        self.acCopy.setText(_translate("MainWindow", "&Copy", None))
        self.acCopy.setShortcut(_translate("MainWindow", "Ctrl+C", None))
        self.acSelectAll.setText(_translate("MainWindow", "Select &All", None))
        self.acSelectAll.setShortcut(_translate("MainWindow", "Ctrl+A", None))
        self.acFind.setText(_translate("MainWindow", "&Find", None))
        self.acFind.setShortcut(_translate("MainWindow", "Ctrl+F", None))
        self.acCompare.setText(_translate("MainWindow", "&Compare Mode", None))
        self.acShowGraph.setText(_translate("MainWindow", "Show &graph", None))
        self.acAboutQt.setText(_translate("MainWindow", "About &Qt", None))

from gitview import GitView
