# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/preferences.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Preferences(object):
    def setupUi(self, Preferences):
        Preferences.setObjectName(_fromUtf8("Preferences"))
        Preferences.resize(529, 316)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Preferences)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(Preferences)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabGeneral = QtGui.QWidget()
        self.tabGeneral.setObjectName(_fromUtf8("tabGeneral"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabGeneral)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_6 = QtGui.QGroupBox(self.tabGeneral)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.cbEsc = QtGui.QCheckBox(self.groupBox_6)
        self.cbEsc.setObjectName(_fromUtf8("cbEsc"))
        self.verticalLayout_5.addWidget(self.cbEsc)
        self.cbState = QtGui.QCheckBox(self.groupBox_6)
        self.cbState.setObjectName(_fromUtf8("cbState"))
        self.verticalLayout_5.addWidget(self.cbState)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.groupBox_5 = QtGui.QGroupBox(self.tabGeneral)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cbShowWhitespace = QtGui.QCheckBox(self.groupBox_5)
        self.cbShowWhitespace.setObjectName(_fromUtf8("cbShowWhitespace"))
        self.horizontalLayout.addWidget(self.cbShowWhitespace)
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.sbTabSize = QtGui.QSpinBox(self.groupBox_5)
        self.sbTabSize.setMinimum(1)
        self.sbTabSize.setMaximum(8)
        self.sbTabSize.setProperty("value", 4)
        self.sbTabSize.setObjectName(_fromUtf8("sbTabSize"))
        self.horizontalLayout.addWidget(self.sbTabSize)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_11 = QtGui.QLabel(self.groupBox_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_3.addWidget(self.label_11)
        self.cbIgnoreWhitespace = QtGui.QComboBox(self.groupBox_5)
        self.cbIgnoreWhitespace.setObjectName(_fromUtf8("cbIgnoreWhitespace"))
        self.cbIgnoreWhitespace.addItem(_fromUtf8(""))
        self.cbIgnoreWhitespace.addItem(_fromUtf8(""))
        self.cbIgnoreWhitespace.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.cbIgnoreWhitespace)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.tabWidget.addTab(self.tabGeneral, _fromUtf8(""))
        self.tabFonts = QtGui.QWidget()
        self.tabFonts.setObjectName(_fromUtf8("tabFonts"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabFonts)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_3 = QtGui.QGroupBox(self.tabFonts)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.cbSizeLog = QtGui.QComboBox(self.groupBox_3)
        self.cbSizeLog.setObjectName(_fromUtf8("cbSizeLog"))
        self.gridLayout_3.addWidget(self.cbSizeLog, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.cbFamilyLog = QtGui.QFontComboBox(self.groupBox_3)
        self.cbFamilyLog.setObjectName(_fromUtf8("cbFamilyLog"))
        self.gridLayout_3.addWidget(self.cbFamilyLog, 0, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.tabFonts)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.cbFamilyDiff = QtGui.QFontComboBox(self.groupBox_4)
        self.cbFamilyDiff.setObjectName(_fromUtf8("cbFamilyDiff"))
        self.gridLayout_4.addWidget(self.cbFamilyDiff, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_4)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 1, 0, 1, 1)
        self.cbSizeDiff = QtGui.QComboBox(self.groupBox_4)
        self.cbSizeDiff.setObjectName(_fromUtf8("cbSizeDiff"))
        self.gridLayout_4.addWidget(self.cbSizeDiff, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.tabFonts, _fromUtf8(""))
        self.tabSummary = QtGui.QWidget()
        self.tabSummary.setObjectName(_fromUtf8("tabSummary"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabSummary)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.tabSummary)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.colorB = ColorWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorB.sizePolicy().hasHeightForWidth())
        self.colorB.setSizePolicy(sizePolicy)
        self.colorB.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.colorB.setObjectName(_fromUtf8("colorB"))
        self.gridLayout.addWidget(self.colorB, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.colorA = ColorWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorA.sizePolicy().hasHeightForWidth())
        self.colorA.setSizePolicy(sizePolicy)
        self.colorA.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.colorA.setObjectName(_fromUtf8("colorA"))
        self.gridLayout.addWidget(self.colorA, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tabSummary)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.leBugUrl = QtGui.QLineEdit(self.groupBox_2)
        self.leBugUrl.setObjectName(_fromUtf8("leBugUrl"))
        self.gridLayout_2.addWidget(self.leBugUrl, 1, 1, 1, 1)
        self.leCommitUrl = QtGui.QLineEdit(self.groupBox_2)
        self.leCommitUrl.setObjectName(_fromUtf8("leCommitUrl"))
        self.gridLayout_2.addWidget(self.leCommitUrl, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.leBugPattern = QtGui.QLineEdit(self.groupBox_2)
        self.leBugPattern.setObjectName(_fromUtf8("leBugPattern"))
        self.gridLayout_2.addWidget(self.leBugPattern, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tabSummary, _fromUtf8(""))
        self.tabTools = QtGui.QWidget()
        self.tabTools.setObjectName(_fromUtf8("tabTools"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tabTools)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_7 = QtGui.QGroupBox(self.tabTools)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_12 = QtGui.QLabel(self.groupBox_7)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_8.addWidget(self.label_12)
        self.tableView = QtGui.QTableView(self.groupBox_7)
        self.tableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.verticalLayout_8.addWidget(self.tableView)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnAdd = QtGui.QPushButton(self.groupBox_7)
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.horizontalLayout_2.addWidget(self.btnAdd)
        self.btnDelete = QtGui.QPushButton(self.groupBox_7)
        self.btnDelete.setObjectName(_fromUtf8("btnDelete"))
        self.horizontalLayout_2.addWidget(self.btnDelete)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addWidget(self.groupBox_7)
        self.tabWidget.addTab(self.tabTools, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Preferences)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.label_10.setBuddy(self.sbTabSize)
        self.label_11.setBuddy(self.cbIgnoreWhitespace)
        self.label_6.setBuddy(self.cbFamilyLog)
        self.label_7.setBuddy(self.cbSizeLog)
        self.label_9.setBuddy(self.cbSizeDiff)
        self.label_8.setBuddy(self.cbFamilyDiff)
        self.label_2.setBuddy(self.colorB)
        self.label.setBuddy(self.colorA)
        self.label_3.setBuddy(self.leCommitUrl)
        self.label_4.setBuddy(self.leBugUrl)
        self.label_5.setBuddy(self.leBugPattern)

        self.retranslateUi(Preferences)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Preferences.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Preferences.reject)
        QtCore.QMetaObject.connectSlotsByName(Preferences)
        Preferences.setTabOrder(self.btnAdd, self.tableView)
        Preferences.setTabOrder(self.tableView, self.cbSizeDiff)
        Preferences.setTabOrder(self.cbSizeDiff, self.colorA)
        Preferences.setTabOrder(self.colorA, self.colorB)
        Preferences.setTabOrder(self.colorB, self.leCommitUrl)
        Preferences.setTabOrder(self.leCommitUrl, self.leBugUrl)
        Preferences.setTabOrder(self.leBugUrl, self.leBugPattern)
        Preferences.setTabOrder(self.leBugPattern, self.buttonBox)
        Preferences.setTabOrder(self.buttonBox, self.cbEsc)
        Preferences.setTabOrder(self.cbEsc, self.cbState)
        Preferences.setTabOrder(self.cbState, self.cbShowWhitespace)
        Preferences.setTabOrder(self.cbShowWhitespace, self.sbTabSize)
        Preferences.setTabOrder(self.sbTabSize, self.cbIgnoreWhitespace)
        Preferences.setTabOrder(self.cbIgnoreWhitespace, self.cbFamilyDiff)
        Preferences.setTabOrder(self.cbFamilyDiff, self.tabWidget)
        Preferences.setTabOrder(self.tabWidget, self.cbFamilyLog)
        Preferences.setTabOrder(self.cbFamilyLog, self.cbSizeLog)

    def retranslateUi(self, Preferences):
        Preferences.setWindowTitle(_translate("Preferences", "Preferences", None))
        self.groupBox_6.setTitle(_translate("Preferences", "Application", None))
        self.cbEsc.setText(_translate("Preferences", "&Quit also via Esc key", None))
        self.cbState.setText(_translate("Preferences", "&Remember window state", None))
        self.groupBox_5.setTitle(_translate("Preferences", "Diff view", None))
        self.cbShowWhitespace.setText(_translate("Preferences", "&Visualize whitespace", None))
        self.label_10.setText(_translate("Preferences", "&Tab size:", None))
        self.label_11.setText(_translate("Preferences", "&Ignore whitespace:", None))
        self.cbIgnoreWhitespace.setItemText(0, _translate("Preferences", "None", None))
        self.cbIgnoreWhitespace.setItemText(1, _translate("Preferences", "At end of line", None))
        self.cbIgnoreWhitespace.setItemText(2, _translate("Preferences", "All", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeneral), _translate("Preferences", "&General", None))
        self.groupBox_3.setTitle(_translate("Preferences", "Log view", None))
        self.label_6.setText(_translate("Preferences", "&Family:", None))
        self.label_7.setText(_translate("Preferences", "&Size:", None))
        self.groupBox_4.setTitle(_translate("Preferences", "Diff view", None))
        self.label_9.setText(_translate("Preferences", "S&ize:", None))
        self.label_8.setText(_translate("Preferences", "F&amily:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFonts), _translate("Preferences", "&Fonts", None))
        self.groupBox.setTitle(_translate("Preferences", "Color", None))
        self.label_2.setText(_translate("Preferences", "Branch &B:", None))
        self.label.setText(_translate("Preferences", "Branch &A:", None))
        self.groupBox_2.setTitle(_translate("Preferences", "Links", None))
        self.label_3.setText(_translate("Preferences", "C&ommit URL:", None))
        self.label_4.setText(_translate("Preferences", "B&UG URL:", None))
        self.label_5.setText(_translate("Preferences", "BUG &Pattern:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSummary), _translate("Preferences", "Co&mmit", None))
        self.groupBox_7.setTitle(_translate("Preferences", "Tools", None))
        self.label_12.setText(_translate("Preferences", "You must add the tool to git config mergetool/difftool section to make it works.", None))
        self.btnAdd.setText(_translate("Preferences", "&Add", None))
        self.btnDelete.setText(_translate("Preferences", "&Delete", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTools), _translate("Preferences", "&Tools", None))

from colorwidget import ColorWidget
